/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Combo {
  id: string;
  name: string;
  structures: string[];
}

export const COMBOS: Combo[] = [
  { id: "1", name: "Picnic", structures: ["Park", "Lunches 2 GO", "Bakery"] },
  { id: "2", name: "Sweets", structures: ["Cakery", "Creperie", "Donut Shop"] },
  { id: "3", name: "Chubby", structures: ["Ramen Bar", "Pizzeria", "Donut Shop"] },
  { id: "4", name: "Eating-Out", structures: ["Steakhouse", "Restaurant", "Fast 'n' Fried"] },
  { id: "5", name: "Groceries", structures: ["Supermarket", "Greengrocer", "Fishmonger"] },
  { id: "6", name: "Lazy Day", structures: ["Blogbuster", "Bowling Alley", "Game Arcade"] },
  { id: "7", name: "Jolly", structures: ["Music Shop", "Florist", "Cakery"] },
  { id: "8", name: "Family", structures: ["Park", "Game Shop", "Toy Shop"] },
  { id: "9", name: "Convenient", structures: ["Supermarket", "24-7 Mart", "Drugstore"] },
  { id: "10", name: "Chill-Out", structures: ["Bookstore", "Cafe", "Florist"] },
  { id: "11", name: "Hi-Tec", structures: ["PC Shop", "Cell Shop", "Home Elec."] },
  { id: "12", name: "Otaku", structures: ["Anime Shop", "Game Shop", "Toy Shop"] },
  { id: "13", name: "Old-Timey", structures: ["Candy Shop", "Shrine", "Sauna"] },
  { id: "14", name: "Seaside", structures: ["Beach House", "Wharf", "Fishmonger"] },
  { id: "15", name: "Local", structures: ["Cakery", "Greengrocer", "Florist"] },
  { id: "16", name: "Student", structures: ["School", "Steakhouse", "Diner"] },
  { id: "17", name: "Lunch", structures: ["Lunches 2 GO", "Bakery", "Cafe"] },
  { id: "18", name: "Silicon", structures: ["Game Shop", "Cell Shop", "PC Shop"] },
  { id: "19", name: "Fishy", structures: ["Fishing Pond", "Fishmonger", "Aquarium"] },
  { id: "20", name: "Lunch-Break", structures: ["Trash Cans", "24-7 Mart", "School"] },
  { id: "21", name: "Telecom", structures: ["Phone Box", "PC Shop", "Cell Shop"] },
  { id: "22", name: "Cheap Lunch", structures: ["Bench", "Gingko", "Fast 'n' Fried"] },
  { id: "23", name: "Family Sunday", structures: ["Fountain", "Creperie", "Zoo"] },
  { id: "24", name: "Pet", structures: ["Doggie Statue", "Beautician", "Pet Shop"] },
  { id: "25", name: "Tourist Spot", structures: ["Clock Tower", "Local Center", "Shrine"] },
  { id: "26", name: "Money Drain", structures: ["Lotto Ticket Shop", "Sushi Joint", "Tapas Bar"] },
  { id: "27", name: "Aqua", structures: ["Fire Hydrant", "Fishing Pond", "Heated Pool"] },
  { id: "28", name: "Teachers", structures: ["Park", "School", "Dry Cleaner"] },
  { id: "29", name: "Bikers", structures: ["Pizzeria", "Motorcycle Shop", "Fast 'n' Fried"] },
  { id: "30", name: "Farm Lunch", structures: ["Lunches 2 GO", "Hydrangeas", "Farm"] },
  { id: "31", name: "Tranquil", structures: ["Pet Shop", "Mountain", "Fishing Pond"] },
  { id: "32", name: "Biker Show", structures: ["Blogbuster", "Motorcycle Shop", "PC Shop"] },
  { id: "33", name: "Meet-Up", structures: ["Cafe", "Diner", "Clock Tower"] },
  { id: "34", name: "Flowery", structures: ["Florist", "Sunflowers", "Ranch"] },
  { id: "35", name: "Picturesque", structures: ["Fishmonger", "Boulder", "Spa Hotel"] },
  { id: "36", name: "Fresh Food", structures: ["Greengrocer", "Restaurant", "Fishmonger"] },
  { id: "37", name: "Clean Tunes", structures: ["Music Shop", "Cell Shop", "Sauna"] },
  { id: "38", name: "Games & Toys", structures: ["Game Shop", "Home Elec.", "Toy Shop"] },
  { id: "39", name: "Movie", structures: ["Anime Shop", "Cinema", "Blogbuster"] },
  { id: "40", name: "Day Off", structures: ["Bookstore", "Bench", "Cafe"] },
  { id: "41", name: "Grandpa", structures: ["Ramen Bar", "Sauna", "Utility Pole"] },
  { id: "42", name: "Education", structures: ["School", "Cram School", "Bookstore"] },
  { id: "43", name: "Housekeeper", structures: ["Supermarket", "Dry Cleaner", "Local Center"] },
  { id: "44", name: "Gamers", structures: ["Game Shop", "PC Shop", "Game Arcade"] },
  { id: "45", name: "Weekend", structures: ["Sushi Joint", "BBQ House", "Pizzeria"] },
  { id: "46", name: "H. Springs", structures: ["Sauna", "Spa", "Spa Hotel"] },
  { id: "47", name: "Health", structures: ["Hospital", "Gym", "Sauna"] },
  { id: "48", name: "Shopping", structures: ["Supermarket", "Boutique", "Jewelry Shop"] },
  { id: "49", name: "Gourmet", structures: ["Tapas Bar", "Sushi Joint", "Ramen Bar"] },
  { id: "50", name: "Fashion (#1)", structures: ["Boutique", "Cakery", "Drugstore"] },
  { id: "51", name: "Intellect", structures: ["Bookstore", "Museum", "School"] },
  { id: "52", name: "Fitness", structures: ["Heated Pool", "Gym", "Drugstore"] },
  { id: "53", name: "Nature", structures: ["Ranch", "Park", "Camp Site"] },
  { id: "54", name: "Fresh-Made", structures: ["Donut Shop", "Ranch", "Creperie"] },
  { id: "55", name: "Musical", structures: ["Music Shop", "Concert Hall", "Blogbuster"] },
  { id: "56", name: "Passing-By", structures: ["Vending Machine", "Farm", "Ancient Pine"] },
  { id: "57", name: "TV", structures: ["Utility Pole", "Comms Tower", "Home Elec."] },
  { id: "58", name: "Alpine Bread", structures: ["Bakery", "Mountain", "Farm"] },
  { id: "59", name: "Anti-Theft", structures: ["Security Inc.", "Home Elec.", "Bank"] },
  { id: "60", name: "Vacation", structures: ["Bowling Alley", "Steakhouse", "Beautician"] },
  { id: "61", name: "Farm 2 Shop", structures: ["Supermarket", "Mountain", "Farm"] },
  { id: "62", name: "Agritourism", structures: ["Farm", "Greengrocer", "Spa"] },
  { id: "63", name: "Soak", structures: ["Heated Pool", "Dry Cleaner", "Sauna"] },
  { id: "64", name: "Day-Off Chill", structures: ["Beautician", "Home Elec.", "Bookstore"] },
  { id: "65", name: "House Move", structures: ["Estate Agent", "Info Center", "Local Center"] },
  { id: "66", name: "Spectator", structures: ["Donut Shop", "Fire Hydrant", "Stadium"] },
  { id: "67", name: "Triple F", structures: ["Furniture Shop", "Fire Hydrant", "Orchard"] },
  { id: "68", name: "Fishing", structures: ["Wharf", "Fishing Pond", "Sushi Joint"] },
  { id: "69", name: "Outdoor Fam", structures: ["Camp Site", "Mountain", "Parking Lot"] },
  { id: "70", name: "Nature Special", structures: ["Fishing Pond", "Gold Trophy", "Fountain"] },
  { id: "71", name: "Small Town", structures: ["Sports Shop", "School", "Candy Shop"] },
  { id: "72", name: "Medicine", structures: ["Clinic", "Drugstore", "24-7 Mart"] },
  { id: "73", name: "Revive", structures: ["Clinic", "Spa", "Sauna"] },
  { id: "74", name: "Splashy", structures: ["Outdoor Pool", "Aquarium", "Fishmonger"] },
  { id: "75", name: "Fashion (#2)", structures: ["Boutique", "Shoe Shop", "Beautician"] },
  { id: "76", name: "Medical", structures: ["Hospital", "Drugstore", "24-7 Mart"] },
  { id: "77", name: "Vehicle", structures: ["Bike Shop", "Motorcycle Shop", "Car Dealer"] },
  { id: "78", name: "Touristy", structures: ["Spa Hotel", "Temple", "Gift Shop"] },
  { id: "79", name: "Rural", structures: ["Farm", "Ranch", "Fishing Pond"] },
  { id: "80", name: "Day Out", structures: ["Museum", "Aquarium", "Cinema"] },
  { id: "81", name: "Bodyguard", structures: ["Security Inc.", "Gym", "Camp Site"] },
  { id: "82", name: "Estate", structures: ["Contractors", "Estate Agent", "Furniture Shop"] },
  { id: "83", name: "Posh", structures: ["Jewelry Shop", "3-Star Hotel", "Bank"] },
  { id: "84", name: "Pleasure", structures: ["Game Arcade", "Bowling Alley", "Casino"] },
  { id: "85", name: "Culture", structures: ["Jewelry Shop", "Museum", "Cinema"] },
  { id: "86", name: "Industry", structures: ["Motorcycle Shop", "Car Dealer", "School"] },
  { id: "87", name: "Animal", structures: ["Pet Shop", "Ranch", "Zoo"] },
  { id: "88", name: "Workaholic", structures: ["Office Bldg", "Hospital", "Dry Cleaner"] },
  { id: "89", name: "Never-Lost", structures: ["Info Center", "Local Center", "Comms Tower"] },
  { id: "90", name: "Kairo", structures: ["Public Restrooms", "Kairo Statue", "Theme Park"] },
  { id: "91", name: "Blessings", structures: ["Monument", "Farm", "Shrine"] },
  { id: "92", name: "Kairo Fun", structures: ["Toy Shop", "PC Shop", "Kairo Bldg"] },
  { id: "93", name: "Security", structures: ["Jewelry Shop", "Security Inc.", "3-Star Hotel"] },
  { id: "94", name: "Engineer", structures: ["Contractors", "Bike Shop", "Rocket Hall"] },
  { id: "95", name: "Media", structures: ["Game Arcade", "Aquarium", "Bowling Alley"] },
  { id: "96", name: "Foodie", structures: ["Cakery", "Ranch", "Farm"] },
  { id: "97", name: "Night Out", structures: ["Dance Club", "Tapas Bar", "Drugstore"] },
  { id: "98", name: "Outdoor", structures: ["BBQ House", "Camp Site", "Beach House"] },
  { id: "99", name: "Office Clerk", structures: ["Shoe Shop", "Office Bldg", "Tapas Bar"] },
  { id: "100", name: "Tech & Nature", structures: ["Rocket Hall", "Cactus", "Flowerbed"] },
  { id: "101", name: "Seaside Tour", structures: ["Tapas Bar", "Beach House", "Castle"] },
  { id: "102", name: "Souvenir", structures: ["Candy Shop", "Monument", "Gift Shop"] },
  { id: "103", name: "Food Special", structures: ["Restaurant", "Bronze Trophy", "Observation Deck"] },
  { id: "104", name: "Spa Special", structures: ["Sauna", "Bronze Trophy", "Observation Deck"] },
  { id: "105", name: "Beef Special", structures: ["Steakhouse", "Bronze Trophy", "Observation Deck"] },
  { id: "106", name: "Temple Special", structures: ["Temple", "Bronze Trophy", "24-7 Mart"] },
  { id: "107", name: "Sweet Special", structures: ["Creperie", "Bronze Trophy", "Observation Deck"] },
  { id: "108", name: "Sport Special", structures: ["Fast 'n' Fried", "Silver Trophy", "Gym"] },
  { id: "109", name: "Car Special", structures: ["Parking Lot", "Silver Trophy", "Car Dealer"] },
  { id: "110", name: "Museum Special", structures: ["Diner", "Silver Trophy", "Museum"] },
  { id: "111", name: "Swimming", structures: ["Outdoor Pool", "Beach House", "Heated Pool"] },
  { id: "112", name: "Outfitters", structures: ["Sports Shop", "Shoe Shop", "Boutique"] },
  { id: "113", name: "Smart", structures: ["Planetarium", "School", "Museum"] },
  { id: "114", name: "Popular", structures: ["Home Center", "Estate Agent", "Supermarket"] },
  { id: "115", name: "Sporty", structures: ["Stadium", "Baseball Park", "Gym"] },
  { id: "116", name: "DIY", structures: ["Dept. Store", "Furniture Shop", "Home Elec."] },
  { id: "117", name: "Grown-Up", structures: ["Dance Club", "Casino", "Tapas Bar"] },
  { id: "118", name: "Oriental", structures: ["Pagoda", "Shrine", "Monument"] },
  { id: "119", name: "Celeb", structures: ["Castle", "Boutique", "Dept. Store"] },
  { id: "120", name: "Business", structures: ["High-Rise", "Skyscraper", "Bank"] },
  { id: "121", name: "Sinister", structures: ["Comms Tower", "Hospital", "School"] },
  { id: "122", name: "Hollywood", structures: ["Cinema", "Theme Park", "Jewelry Shop"] },
  { id: "123", name: "Kairo Park", structures: ["Kairo Statue", "Game Shop", "Kairo Bldg"] },
  { id: "124", name: "Cyclists", structures: ["Bike Shop", "Gym", "Stadium"] },
  { id: "125", name: "Live Gig", structures: ["Cell Shop", "Comms Tower", "Concert Hall"] },
  { id: "126", name: "Cram Combo", structures: ["Cram School", "Stadium", "Gym"] },
  { id: "127", name: "Spring Deal", structures: ["Boutique", "Cherry Tree", "Dept. Store"] },
  { id: "128", name: "Safe Flight", structures: ["Shrine", "Airport", "Security Inc."] },
  { id: "129", name: "Schoolday", structures: ["Drugstore", "School", "Subway"] },
  { id: "130", name: "Time-Saver", structures: ["Dry Cleaner", "Furniture Shop", "Subway"] },
  { id: "131", name: "Easy Tour", structures: ["Gift Shop", "Subway", "Pagoda"] },
  { id: "132", name: "Healthcare", structures: ["Local Center", "Hospital", "Subway"] },
  { id: "133", name: "Hot Events", structures: ["Concert Hall", "Parking Lot", "Baseball Park"] },
  { id: "134", name: "Surveillance", structures: ["Helipad", "Security Inc.", "PC Shop"] },
  { id: "135", name: "Sea Special", structures: ["Sushi Joint", "Bronze Trophy", "Observation Deck"] },
  { id: "136", name: "Money Special", structures: ["Casino", "Bronze Trophy", "Observation Deck"] },
  { id: "137", name: "Rich Special", structures: ["24-7 Mart", "Silver Trophy", "Casino"] },
  { id: "138", name: "Shop Special", structures: ["Bus Stop", "Silver Trophy", "Dept. Store"] },
  { id: "139", name: "Historic Special", structures: ["Museum", "Silver Trophy", "Castle"] },
  { id: "140", name: "Bike Special", structures: ["Motorcycle Shop", "Silver Trophy", "Kairo Bldg"] },
  { id: "141", name: "Farm Special", structures: ["Spa", "Gold Trophy", "Ranch"] },
  { id: "142", name: "Fun Special", structures: ["Beach House", "Gold Trophy", "Theme Park"] },
  { id: "143", name: "Movie Special", structures: ["Dept. Store", "Gold Trophy", "Cinema"] },
  { id: "144", name: "Golf", structures: ["Golf Training Center", "Golf Course", "Sports Shop"] },
  { id: "145", name: "Suburb", structures: ["Home Center", "Farm", "PC Shop"] },
  { id: "146", name: "Athletic", structures: ["Sports Grounds", "Gym", "Stadium"] },
  { id: "147", name: "Hole-in-One", structures: ["Golf Training Center", "Gold Trophy", "Donut Shop"] },
  { id: "148", name: "Training", structures: ["Sports Grounds", "Gold Trophy", "Baseball Park"] },
  { id: "149", name: "Furry Critter", structures: ["Safari Park", "Kairopuppy Statue", "Pet Shop"] },
  { id: "150", name: "Eventful", structures: ["Cinema", "Theme Park", "Concert Hall"] },
  { id: "151", name: "Critter", structures: ["Aquarium", "Zoo", "Ranch"] },
  { id: "152", name: "Amusement", structures: ["Comms Tower", "TV Station", "Concert Hall"] },
  { id: "153", name: "High-Rise", structures: ["High-Rise", "Skyscraper", "Kairo Bldg"] },
  { id: "154", name: "Castle", structures: ["Palace", "Castle", "Kairo Statue"] },
  { id: "155", name: "Aviation", structures: ["Rocket Hall", "Helipad", "Airport"] },
  { id: "156", name: "Date", structures: ["Theme Park", "Zoo", "Cinema"] },
  { id: "157", name: "Special", structures: ["Airport", "TV Station", "Skyscraper"] },
  { id: "158", name: "Consortium", structures: ["Office Tower", "Weeping Cherry", "High-Rise"] },
  { id: "159", name: "Big Bucks", structures: ["Kairo Statue", "Office Tower", "BBQ House"] },
  { id: "160", name: "Subway", structures: ["Subway", "Office Tower", "High-Rise"] },
  { id: "161", name: "Castle Special", structures: ["Palace", "Gold Trophy", "3-Star Hotel"] },
  { id: "162", name: "Cherry Special", structures: ["3-Star Hotel", "Gold Trophy", "Weeping Cherry"] },
  { id: "163", name: "Sushi Special", structures: ["Comms Tower", "Gold Trophy", "Sushi Joint"] },
  { id: "164", name: "Ducky", structures: ["Ducky Statue", "Gold Trophy", "Pagoda"] },
  { id: "165", name: "Ackbar", structures: ["Ackbar Statue", "Gold Trophy", "Kairo Bldg"] },
  { id: "166", name: "Kairoman", structures: ["Kairoman Statue", "Gold Trophy", "Cinema"] },
  { id: "167", name: "Kairopuppy", structures: ["Kairopuppy Statue", "Gold Trophy", "Hospital"] },
  { id: "168", name: "Kairodad", structures: ["Kairodad Statue", "Gold Trophy", "TV Station"] },
  { id: "169", name: "Bearington", structures: ["Bearington Statue", "Gold Trophy", "Home Elec."] },
  { id: "170", name: "Sally Prin", structures: ["Sally Prin Statue", "Gold Trophy", "Spa Hotel"] },
  { id: "171", name: "Chimpan Z", structures: ["Chimpan Z Statue", "Gold Trophy", "Gym"] },
  { id: "172", name: "Pumpkin", structures: ["Pumpkin Statue", "Gold Trophy", "Car Dealer"] },
  { id: "173", name: "Secretary", structures: ["Secretary Statue", "Gold Trophy", "Theme Park"] },
  { id: "174", name: "Sheepy", structures: ["Sheepy Statue", "Gold Trophy", "School"] },
  { id: "175", name: "Octo-Alien", structures: ["Octo-Alien Statue", "Gold Trophy", "Stadium"] },
  { id: "176", name: "Minnie", structures: ["Minnie Statue", "Gold Trophy", "Aquarium"] },
  { id: "177", name: "Wariobot", structures: ["Wariobot Statue", "Gold Trophy", "Ranch"] },
  { id: "178", name: "Bunny", structures: ["Bunny Statue", "Gold Trophy", "Baseball Park"] },
  { id: "179", name: "Angelic Kairobot", structures: ["Angelic Kairo Statue", "Gold Trophy", "Zoo"] },
  { id: "180", name: "Space", structures: ["Planetarium", "Rocket Hall", "Octo-Alien Statue"] },
  { id: "181", name: "Animal Love", structures: ["Safari Park", "Zoo", "Aquarium"] },
  { id: "182", name: "Livestock", structures: ["Racecourse", "Ranch", "Zoo"] },
  { id: "183", name: "Corporate", structures: ["Golf Course", "Kairodad Statue", "Tapas Bar"] },
  { id: "184", name: "Big-Spender", structures: ["Racecourse", "Ackbar Statue", "Casino"] },
  { id: "185", name: "Hill", structures: ["Fountain Plaza", "Spa Hotel", "Camp Site"] },
  { id: "186", name: "Smiley", structures: ["Fountain Plaza", "Theme Park", "Sally Prin Statue"] }
];
